In [1]:
import pandas as pd

In [2]:
def filter_by_regular(filename):
    '''
    This function should read the csv file located at filename into a pandas dataframe,
    and filter the dataframe to only rows where the 'DESCn' column has the value 'REGULAR'.
    
    For example, if the pandas dataframe is as follows:
    ,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn
    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    1,A002,R051,02-00-00,05-01-11,04:00:00,DOOR,3144335,1088159
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177
    3,A002,R051,02-00-00,05-01-11,12:00:00,DOOR,3144424,1088231
    
    The dataframe will look like below after filtering to only rows where DESCn column
    has the value 'REGULAR':
    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177
    '''
    df = pd.read_csv(filename) 
    turnstile_data = df[df.DESCn == 'REGULAR']
    return turnstile_data

In [3]:
filename = 'input_data/turnstile_data_master_subset_regular.csv'

In [4]:
filter_by_regular(filename)

,Unnamed: 0,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn
0,0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
1,1,A002,R051,02-00-00,05-01-11,04:00:00,REGULAR,3144335,1088159
2,2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177
3,3,A002,R051,02-00-00,05-01-11,12:00:00,REGULAR,3144424,1088231
4,4,A002,R051,02-00-00,05-01-11,16:00:00,REGULAR,3144594,1088275
5,5,A002,R051,02-00-00,05-01-11,20:00:00,REGULAR,3144808,1088317
6,6,A002,R051,02-00-00,05-02-11,00:00:00,REGULAR,3144895,1088328
7,7,A002,R051,02-00-00,05-02-11,04:00:00,REGULAR,3144905,1088331
8,8,A002,R051,02-00-00,05-02-11,08:00:00,REGULAR,3144941,1088420
9,9,A002,R051,02-00-00,05-02-11,12:00:00,REGULAR,3145094,1088753
10,10,A002,R051,02-00-00,05-02-11,16:00:00,REGULAR,3145337,1088823
11,11,A002,R051,02-00-00,05-02-11,20:00:00,REGULAR,3146168,1088888
12,12,A002,R051,02-00-00,05-03-11,00:00:00,REGULAR,3146322,1088918
13,13,A002,R051,02-00-00,05-03-11,04:00:00,REGULAR,3146335,1088921
14,14,A002,R051,02-00-00,05-03-11,08:00:00,REGULAR,3146371,1089014
15,15,A002,R051,02-00-00,05-03-11,12:00:00,REGULAR,3146510,1089341
16,16,A002,R051,02-00-00,05-03-11,16:00:00,REGULAR,3146790,1089417
17,17,A002,R051,02-00-00,05-03-11,20:00:00,REGULAR,3147615,1089478
18,18,A002,R051,02-00-00,05-04-11,00:00:00,REGULAR,3147798,1089515
19,19,A002,R051,02-00-00,05-04-11,04:00:00,REGULAR,3147809,1089520
20,20,A002,R051,02-00-00,05-04-11,08:00:00,REGULAR,3147859,1089632
21,21,A002,R051,02-00-00,05-04-11,12:00:00,REGULAR,3147999,1089965
22,22,A002,R051,02-00-00,05-04-11,16:00:00,REGULAR,3148276,1090054
23,23,A002,R051,02-00-00,05-04-11,20:00:00,REGULAR,3149108,1090117
24,24,A002,R051,02-00-00,05-05-11,00:00:00,REGULAR,3149281,1090139
25,25,A002,R051,02-00-00,05-05-11,04:00:00,REGULAR,3149297,1090145
26,26,A002,R051,02-00-00,05-05-11,08:00:00,REGULAR,3149331,1090257
27,34,A002,R051,02-00-00,05-05-11,20:00:00,REGULAR,3150639,1090714
28,35,A002,R051,02-00-00,05-06-11,00:00:00,REGULAR,3150815,1090750
29,36,A002,R051,02-00-00,05-06-11,04:00:00,REGULAR,3150840,1090759
...,...,...,...,...,...,...,...,...,...
4202,4956,A034,R170,03-06-00,05-01-11,09:00:00,REGULAR,9164155,5796594
4203,4957,A034,R170,03-06-00,05-01-11,13:00:00,REGULAR,9164311,5796677
4204,4958,A034,R170,03-06-00,05-01-11,17:00:00,REGULAR,9164569,5796765
4205,4959,A034,R170,03-06-00,05-01-11,21:00:00,REGULAR,9164769,5796838
4206,4960,A034,R170,03-06-00,05-02-11,01:00:00,REGULAR,9164854,5796848
4207,4961,A034,R170,03-06-00,05-02-11,05:00:00,REGULAR,9164859,5796849
4208,4962,A034,R170,03-06-00,05-02-11,09:00:00,REGULAR,9164941,5796900
4209,4963,A034,R170,03-06-00,05-02-11,13:00:00,REGULAR,9165124,5796959
4210,4964,A034,R170,03-06-00,05-02-11,17:00:00,REGULAR,9165461,5797136
4211,4965,A034,R170,03-06-00,05-02-11,21:00:00,REGULAR,9165857,5797317
4212,4966,A034,R170,03-06-00,05-03-11,01:00:00,REGULAR,9165949,5797327
4213,4967,A034,R170,03-06-00,05-03-11,05:00:00,REGULAR,9165956,5797327
4214,4968,A034,R170,03-06-00,05-03-11,09:00:00,REGULAR,9166043,5797368
4215,4974,A034,R170,03-06-00,05-03-11,21:00:00,REGULAR,9167110,5797892
4216,4975,A034,R170,03-06-00,05-04-11,01:00:00,REGULAR,9167276,5797906
4217,4976,A034,R170,03-06-00,05-04-11,05:00:00,REGULAR,9167293,5797907
4218,4977,A034,R170,03-06-00,05-04-11,09:00:00,REGULAR,9167375,5797946
4219,4978,A034,R170,03-06-00,05-04-11,13:00:00,REGULAR,9167531,5798020
4220,4979,A034,R170,03-06-00,05-04-11,17:00:00,REGULAR,9167797,5798161
4221,4980,A034,R170,03-06-00,05-04-11,21:00:00,REGULAR,9168228,5798360
4222,4981,A034,R170,03-06-00,05-05-11,01:00:00,REGULAR,9168382,5798378
4223,4982,A034,R170,03-06-00,05-05-11,05:00:00,REGULAR,9168395,5798380
4224,4983,A034,R170,03-06-00,05-05-11,09:00:00,REGULAR,9168483,5798410
4225,4984,A034,R170,03-06-00,05-05-11,13:00:00,REGULAR,9168683,5798510
4226,4985,A034,R170,03-06-00,05-05-11,17:00:00,REGULAR,9169064,5798683
4227,4986,A034,R170,03-06-00,05-05-11,21:00:00,REGULAR,9169547,5798956
4228,4991,A034,R170,03-06-00,05-06-11,05:00:00,REGULAR,9169787,5799002
4229,4995,A034,R170,03-06-00,05-06-11,21:00:00,REGULAR,9171025,5799732
4230,4996,A034,R170,03-06-01,05-01-11,01:00:00,REGULAR,5604407,2448624
4231,4997,A034,R170,03-06-01,05-01-11,05:00:00,REGULAR,5604511,2448644